let getTVShows = function() {
    return [
        { id: 'maninthehighcastle', name: 'The Man in the High Castle',
         synopsis: 'The Man in the High Castle is a 1962 novel by Philip K. Dick. In this alternative history novel, Dick imagines a world in which the Axis powers won World War II and Nazi Germany shares joint control of the United States with Imperial Japan. The book follows three groups of characters as they navigate this dangerous, authoritarian world. The novel is highly regarded by critics, and won the Hugo Award for Best Novel in 1963. In 2015, the book was adapted into a multi-season television series.' },
        { id: 'thebureau', name: 'The Bureau', 
        synopsis: `The Bureau is based upon real accounts by former spies and inspired by contemporary events, and centres on the daily life and missions of agents within France's Directorate-General for External Security, its principal external security service. It focuses on the "Bureau of Legends", responsible for training and handling deep-cover agents (operating 'under legend') on long-term missions in areas with French interests, especially in North Africa and the Middle East. Living under false identities for years, these agents' missions are to identify and recruit good intelligence sources.` },
        { id: 'mrrobot', name: 'Mr. Robot', 
        synopsis: `The series follows Elliot Alderson, a young man living in New York City, who works at the cyber security company Allsafe as a security engineer. Constantly struggling with social anxiety disorder, dissociative identity disorder and clinical depression, Elliot's thought process seems heavily influenced by paranoia and delusion. He connects to people by hacking them, which often leads him to act as a cyber-vigilante. He is recruited by a mysterious insurrectionary anarchist known as Mr. Robot and joins his team of hacktivists known as fsociety. One of their missions is to cancel all consumer debt by destroying the data of one of the largest corporations in the world, E Corp (which Elliot perceives as Evil Corp), which also happens to be Allsafe's biggest client.` },
        { id: 'flash', name: 'Flash', 
        synopsis: `After being struck by lightning, Barry Allen wakes up from his coma to discover he's been given the power of super speed, becoming the Flash, fighting crime in Central City. Barry Allen is a Central City police forensic scientist with a reasonably happy life, despite the childhood trauma of a mysterious red and yellow lightning killing his mother and framing his father. All that changes when a massive particle accelerator accident leads to Barry being struck by lightning in his lab. Coming out of coma nine months later, Barry and his new friends at S.T.A.R labs find that he now has the ability to move at superhuman speed. Furthermore, Barry learns that he is but one of many affected by that event, most of whom are using their powers for evil. Determined to make a difference, Barry dedicates his life to fighting such threats, as The Flash. While he gains allies he never expected, there are also secret forces determined to aid and manipulate him for their own agenda.` },
        { id: 'jackryan', name: 'Jack Ryan', 
        synopsis: `An up-and-coming CIA analyst, Jack Ryan, is thrust into a dangerous field assignment as he uncovers a pattern in terrorist communication that launches him into the center of a dangerous gambit. When CIA analyst Jack Ryan stumbles upon a suspicious series of bank transfers his search for answers pulls him from the safety of his desk job and catapults him into a deadly game of cat and mouse throughout Europe and the Middle East, with a rising terrorist figurehead preparing for a massive attack against the US and her allies.` },
        { id: 'haltandcatchfire', name: 'Halt and Catch Fire', 
        synopsis: `The early 1980s was the early heyday of the technological revolution. Silicon Prairie, centered on Dallas, was one area in the US where much of the activity in this sector was happening. There were a few "name" corporate players in each sector, such as International Business Machines (IBM) in personal computers (PC), Xerox in document management, and Texas Instruments (TI) in semiconductors. Standard corporate practice was to improve technology gradually and charge customers a premium for successive technologically advanced models of products. Within this framework, there were many dreamers, often working in smaller companies or for themselves, who wanted their small, or not so small, piece of the pie, whether it be for fortune and/or fame, the latter often in having a lasting legacy. Those dreams also varied, from only doing things better than their competitors, however small, to producing things that were revolutionary for the time, that made the general public go "wow", as were the rationale for those dreams.` }
    ];
}

module.exports = getTVShows; 